[tools]
node = "24.17.0"
"npm:@devcontainers/cli" = "0.87.0"
biome = "2.5.10"
deno = "2.9.5"
pre-commit = "4.6.2"
python = "3.14.6"
ruby = "4.0.5"
terraform = "1.15.9"
tflint = "0.64.0"
trivy = "0.74.0"
gcloud = "582.0.0"
bun = "1.4.0"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
experimental = true
